In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import (NeighborhoodComponentsAnalysis,KNeighborsClassifier)
from sklearn.preprocessing import Imputer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import math
from sklearn.impute import SimpleImputer

In [36]:
# Loading data
dataset = pd.read_csv('C:\\Users\\User\\Desktop\\creditcardfraud\\creditcard.csv')

In [37]:
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [38]:
x = dataset.iloc[: , 1:30].values
y = dataset.iloc[:, -1].values

In [39]:
print("Input Shape : ", x.shape)
print("Output Shape : ", y.shape)

Input Shape :  (284807, 29)
Output Shape :  (284807,)


In [40]:
print ("Labels : \n", y)

Labels : 
 [0 0 0 ... 0 0 0]


In [41]:
print("Data :\n",x)

Data :
 [[-1.35980713e+00 -7.27811733e-02  2.53634674e+00 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 1.19185711e+00  2.66150712e-01  1.66480113e-01 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [-1.35835406e+00 -1.34016307e+00  1.77320934e+00 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [ 1.91956501e+00 -3.01253846e-01 -3.24963981e+00 ...  4.45477214e-03
  -2.65608286e-02  6.78800000e+01]
 [-2.40440050e-01  5.30482513e-01  7.02510230e-01 ...  1.08820735e-01
   1.04532821e-01  1.00000000e+01]
 [-5.33412522e-01 -1.89733337e-01  7.03337367e-01 ... -2.41530880e-03
   1.36489143e-02  2.17000000e+02]]


In [45]:
imputer = Imputer(missing_values="NaN", strategy="mean", axis=0)
imputer = imputer.fit(x[:, 1:30])
x[:, 1:30] = imputer.fit_transform(x[:, 1:30])

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [52]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.25, random_state = 0)

In [53]:
print("xtrain.shape : ", xTrain.shape)
print("xtest.shape  : ", xTest.shape)
print("ytrain.shape : ", yTrain.shape)
print("ytest.shape  : ", yTest.shape)

xtrain.shape :  (213605, 29)
xtest.shape  :  (71202, 29)
ytrain.shape :  (213605,)
ytest.shape  :  (71202,)


In [64]:
logisticRegressor = LogisticRegression(random_state=0, solver='lbfgs')

In [71]:
logisticRegressor.fit(xTrain, yTrain)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [90]:
yPredictionLR = logisticRegressor.predict(xTest)

In [91]:
print(yPredictionLR)

[0 0 0 ... 0 0 0]


In [92]:
confusionMatrixLR = confusion_matrix(yTest, yPredictionLR)
print("confusion Marix : \n", confusionMatrixLR)

confusion Marix : 
 [[71072    10]
 [   40    80]]


In [109]:
AccuracyLR = ((confusionMatrixLR[0][0] + confusionMatrixLR[1][1]) / confusionMatrixLR.sum())
print("Accuracy of Logestic Regression : ", AccuracyLR)

ErrorRateLR = ((confusionMatrixLR[0][1] + confusionMatrixLR[1][0]) / confusionMatrixLR.sum())
print("Error rate of Logestic Regression  : ", ErrorRateLR)

PrecisionLR=(confusionMatrixLR[0][0] / (confusionMatrixLR[0][0] + confusionMatrixLR[0][1]))
print("Precision of Logestic Regression  : ", PrecisionLR)

TruePositiveRateLR=(confusionMatrixLR[0][0] / (confusionMatrixLR[0][0] + confusionMatrixLR[1][0]))
print("True Positive Rate of Logestic Regression  : ", TruePositiveRateLR)

TrueNegativeRateLR=(confusionMatrixLR[1][1] / (confusionMatrixLR[1][1] + confusionMatrixLR[0][1]))
print("True Negative Rate of Logestic Regression  : ", TrueNegativeRateLR)

F1ScoreLR=((2*PrecisionLR*TruePositiveRateLR) / (PrecisionLR + TruePositiveRateLR))
print("F1 Score of Logestic Regression  : ", F1ScoreLR)

MccLR=(confusionMatrixLR[0][0]*confusionMatrixLR[1][1]-confusionMatrixLR[0][1]*confusionMatrixLR[1][0])/((confusionMatrixLR[0][0]+confusionMatrixLR[0][1])*(confusionMatrixLR[1][0]+confusionMatrixLR[1][1])*(confusionMatrixLR[0][0]+confusionMatrixLR[1][0])*(confusionMatrixLR[0][1]+confusionMatrixLR[1][1]))**0.5
print("Matthew Correlation Coefficient score of Logestic Regression  : ", MccLR)

Accuracy of Logestic Regression :  0.9992977725344794
Error rate of Logestic Regression  :  0.0007022274655206314
Precision of Logestic Regression  :  0.9998593174080639
True Positive Rate of Logestic Regression  :  0.9994375070311621
True Negative Rate of Logestic Regression  :  0.8888888888888888
F1 Score of Logestic Regression  :  0.99964836772297
Matthew Correlation Coefficient score of Logestic Regression  :  0.7694755520613834


In [93]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(xTrain, yTrain)
yPredictionKNN = knn.predict(xTest)

In [94]:
print(yPredictionKNN)

[0 0 0 ... 0 0 0]


In [95]:
confusionMatrixKNN = confusion_matrix(yTest, yPredictionKNN)
print("confusion Marix : \n", confusionMatrixKNN)

confusion Marix : 
 [[71075     7]
 [   34    86]]


In [111]:
AccuracyKNN = ((confusionMatrixKNN[0][0] + confusionMatrixKNN[1][1]) / confusionMatrixKNN.sum())
print("Accuracy of  KNN : ", AccuracyKNN)

ErrorRateKNN = ((confusionMatrixKNN[0][1] + confusionMatrixKNN[1][0]) / confusionMatrixKNN.sum())
print("Error rate of KNN  : ", ErrorRateKNN)

MccKNN=(confusionMatrixKNN[0][0]*confusionMatrixKNN[1][1]-confusionMatrixKNN[0][1]*confusionMatrixKNN[1][0])/((confusionMatrixKNN[0][0]+confusionMatrixKNN[0][1])*(confusionMatrixKNN[1][0]+confusionMatrixKNN[1][1])*(confusionMatrixKNN[0][0]+confusionMatrixKNN[1][0])*(confusionMatrixKNN[0][1]+confusionMatrixKNN[1][1]))**0.5
print("Matthew Correlation Coefficient score of Logestic Regression  : ", MccKNN)

Accuracy of  KNN :  0.9994241734782731
Error rate of KNN  :  0.0005758265217269177
Matthew Correlation Coefficient score of Logestic Regression  :  0.813812220044872


In [98]:
dtClassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtClassifier.fit(xTrain, yTrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [99]:
yPredictionDT = dtClassifier.predict(xTest)

In [100]:
print(yPredictionDT)

[0 0 0 ... 0 0 0]


In [101]:
confusionMatrixDT = confusion_matrix(yTest, yPredictionDT)
print("confusion Marix : \n", confusionMatrixDT)

confusion Marix : 
 [[71052    30]
 [   25    95]]


In [112]:
AccuracyDT = ((confusionMatrixDT[0][0] + confusionMatrixDT[1][1]) / confusionMatrixDT.sum()) *100
print("Accuracy of  DT : ", AccuracyDT)

ErrorRateDT = ((confusionMatrixDT[0][1] + confusionMatrixDT[1][0]) / confusionMatrixDT.sum()) *100
print("Error rate of DT  : ", ErrorRateDT)

MccDT=(confusionMatrixDT[0][0]*confusionMatrixDT[1][1]-confusionMatrixDT[0][1]*confusionMatrixDT[1][0])/((confusionMatrixDT[0][0]+confusionMatrixDT[0][1])*(confusionMatrixDT[1][0]+confusionMatrixDT[1][1])*(confusionMatrixDT[0][0]+confusionMatrixDT[1][0])*(confusionMatrixDT[0][1]+confusionMatrixDT[1][1]))**0.5
print("Matthew Correlation Coefficient score of Logestic Regression  : ", MccDT)

Accuracy of  DT :  99.92275497879272
Error rate of DT  :  0.07724502120726946
Matthew Correlation Coefficient score of Logestic Regression  :  0.7752854989751096
